### ISSUE TITLE
Nouveau message d'erreur, compilation du code après les dernières modifications

### ISSUE THREAD

**Issue by ElaneKou** [sciunto-org/pendantdrop#31]
J'ai compilé le code ce matin et j'ai obtenu ce message d'erreur : 

TypeError : deviation_edge_model_simple() missing 1 required positional argument: 'calib' 

Je n'avais fait aucune modification.

**Comment by sciunto** [comment]
Hum, ca fonctionne pour moi.

* Vérifie que tu es bien synchro sur upstream/master
* Vérifie bien que ton script a les changements d'API. Ils doivent correspondre à ça : https://github.com/sciunto-org/pendantdrop/blob/master/main.py#L50

**Comment by ElaneKou** [comment]
Bonjour, 
j'ai recopié le code que vous m'avez envoyé et maintenant ça fonctionne merci. Je cherche encore pourquoi la version que j'avais ne fonctionne pas. 

Cordialement, 
Elane KOUADOU 



De: "François Boulogne" <notifications@github.com> 
À: "sciunto-org/pendantdrop" <pendantdrop@noreply.github.com> 
Cc: "ElaneKou" <elane.kouadou@u-psud.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mercredi 20 Mai 2020 10:46:47 
Objet: Re: [sciunto-org/pendantdrop] Nouveau message d'erreur, compilation du code après les dernières modifications (#31) 





Hum, ca fonctionne pour moi. 

    * Vérifie que tu es bien synchro sur upstream/master 
    * Vérifie bien que ton script a les changements d'API. Ils doivent correspondre à ça : [ https://github.com/sciunto-org/pendantdrop/blob/master/main.py#L50 | https://github.com/sciunto-org/pendantdrop/blob/master/main.py#L50 ]

**Comment by sciunto** [comment]
Super ! :)
